<?php
return array(
	'group'=>array(//配置在表单中的键名 ,这个会是config[group]
		'type'=>'group',
		'options'=>array(
			'basicsettings'=>array(
				'title'=>'基本设置',
				'options'=>array(
					'codelogin'=>array(
						'title'=>'是否启用采集插件:',
						'type'=>'radio',
						'options'=>array(
							'1'=>'开启',
							'0'=>'关闭'
						),
						'value'=>1,
						'tip'=>'必须在这里开启以后才能使用此功能'
					)
				)
			),
			'developer'=>array(
				'title'=>'基础配置',
				'options'=>array(
					/*'NEXT'=>array(
						'title'=>'采集间隔时间:',
						'type'=>'radio',
						'options'=>array(
							'30'=>'30秒',
							'60'=>'60秒',
							'120'=>'120秒',
							'300'=>'300秒'
						),
						'value'=>30,	
						'tip'=>'采集间隔时间(默认间隔30秒进行一次采集)'
					),*/
                    'KEYWORDS'=>array(
						'title'=>'关键词:',
						'type'=>'textarea',
						'value'=>'',	
						'tip'=>'关键词(要采集的文章所包含的关键词，多个关键词用“|”分割)'
					),
					'URL'=>array(
						'title'=>'目标地址:',
						'type'=>'textarea',		 
						'value'=>'',
						'tip'=>'所要采集的目标网址（多个网址词用数字加“@”分割，如：2@http://www.topthink.com/）'
					),
					'LIST'=>array(
						'title'=>'列表规则:',
						'type'=>'textarea',
						'value'=>'',	
						'tip'=>'正则规则(采集列表页面规则，多个正则词用数字加“@”分割)'
					),
                                        'TITLE'=>array(
						'title'=>'标题规则:',
						'type'=>'textarea',
						'value'=>'',	
						'tip'=>'正则规则(采集标题规则，多个正则词用数字加“@”分割)'
					),
					'CONTENT'=>array(
						'title'=>'终端规则:',
						'type'=>'textarea',
						'value'=>'',	
						'tip'=>'正则规则(采集正文规则，多个正则词用数字加“@”分割)'
					),
				)
			),
		)
	),
);
	
